force-app/main/default/objects/MergeEvent__e/MergeEvent__e.object-meta.xml
<CustomObject>
    <description
  >Custom Event for merging Objects. Accomplished with APEX. Must implement Trigger to create MergeEvent__e per Object.</description>
    <label>Merge Event</label>
    <pluralLabel>Merge Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/MergeEvent__e/fields/MasterRecordID__c.field-meta.xml
<CustomField>
    <fullName>MasterRecordID__c</fullName>
    <description>Record that persists after a merge</description>
    <label>Master Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MergeEvent__e/fields/MergedDate__c.field-meta.xml
<CustomField>
    <fullName>MergedDate__c</fullName>
    <description>Date the Merge occurred</description>
    <label>Merged Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MergeEvent__e/fields/MergedRecordID__c.field-meta.xml
<CustomField>
    <fullName>MergedRecordID__c</fullName>
    <description>The old record id that was deleted and merged into another.</description>
    <label>Merged Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MergeEvent__e/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Name of the Object that was Merged</description>
    <label>ObjectName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountMergeEventHandler.cls
public with sharing class AccountMergeEventHandler {

    @TestVisible private static List<MergeEvent__e> mergeEvents= new List<MergeEvent__e>();

    public static void handleMerge(List<Account> accts) {

        for (Account acct : accts) {
            if(acct.MasterRecordId != null) { // checks if this acct was the loser in a merge
                MergeEvent__e mergeEvent = new MergeEvent__e(
                    ObjectName__c = 'Account',
                    MergedRecordID__c = acct.Id,
                    MasterRecordID__c = acct.MasterRecordId,
                    MergedDate__c = System.now()
                );
                mergeEvents.add(mergeEvent);
            }
        }
        if(!mergeEvents.isEmpty()) {
            EventBus.publish(mergeEvents);
        }
    }
}